name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: cd lab4 && make build
    - name: run and verify
      run: |
        cd lab4
        ./fibo | tee output.txt
        grep -w 55 output.txt
        grep -w 1.618034 output.txt
    - name: unit tests
      run: cd lab4 && make test
